# Application bindings
$terminal = uwsm app -- $TERMINAL
$browser = zen-browser
#$browser = omarchy-launch-browser

bindd = SUPER, Q, Terminal Float, exec, $terminal --dir="$(omarchy-cmd-terminal-cwd)"
bindd = SUPER SHIFT, Q, Terminal Tiled, exec, setsid uwsm app -- alacritty --class=Omarchy
bindd = SUPER, E, File manager, exec, uwsm app -- nautilus --new-window
bindd = SUPER, B, Browser, exec, $browser
bindd = SUPER SHIFT, B, Browser (private), exec, $browser --private
bindd = SUPER, M, Music, exec, omarchy-launch-or-focus spotify-launcher
bindd = SUPER, N, Editor, exec, omarchy-launch-editor
bindd = SUPER, T, Activity, exec, omarchy-launch-tui btop
bindd = SUPER, G, Signal, exec, omarchy-launch-or-focus signal "uwsm app -- signal-desktop"
#bindd = SUPER, O, Obsidian, exec, omarchy-launch-or-focus obsidian "uwsm app -- obsidian -disable-gpu --enable-wayland-ime"
bindd = SUPER, O, Obsidian, exec, obsidian
bind = SUPER, S, swapactiveworkspaces, 0 1

bindd = SUPER , F, Fullscreen, fullscreen

bindd = SUPER, R, Application Launcher, exec, walker 
unbind = SUPER, W
bind = SUPER, C, killactive

unbind = SUPER, H
unbind = SUPER, L
unbind = SUPER, K
unbind = SUPER, J
bindd = SUPER, H, Move window focus left, movefocus, l
bindd = SUPER, L, Move window focus right, movefocus, r
bindd = SUPER, K, Move window focus up, movefocus, u
bindd = SUPER, J, Move window focus down, movefocus, d

unbind = SUPER SHIFT, H
unbind = SUPER SHIFT, L
unbind = SUPER SHIFT, K
unbind = SUPER SHIFT, J
bindd = SUPER SHIFT, H, Swap window to the left, swapwindow, l
bindd = SUPER SHIFT, L, Swap window to the right, swapwindow, r
bindd = SUPER SHIFT, K, Swap window up, swapwindow, u
bindd = SUPER SHIFT, J, Swap window down, swapwindow, d

bindd = SUPER, D, Toggle Floating, togglefloating

bindmd = SUPER, A, Resize window, resizewindow

#Overwrite existing bindings, like putting Omarchy Menu on Super + Space
unbind = SUPER, SPACE
bindd = SUPER, SPACE, Omarchy menu, exec, omarchy-menu

unbind = SUPER, TAB
bind = SUPER, TAB, global, quickshell:hubToggle

bind = SUPER, O, exec, obsidian
